# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/setuthacker/Xilink_Projects/Multirate_DSP_Final/Multirate_DSP_Final.srcs/sources_1/ip/fir_decimator/fir_decimator.xci
# IP: The module: 'fir_decimator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/setuthacker/Xilink_Projects/Multirate_DSP_Final/Multirate_DSP_Final.gen/sources_1/ip/fir_decimator/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_decimator'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/setuthacker/Xilink_Projects/Multirate_DSP_Final/Multirate_DSP_Final.gen/sources_1/ip/fir_decimator/fir_decimator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_decimator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/setuthacker/Xilink_Projects/Multirate_DSP_Final/Multirate_DSP_Final.srcs/sources_1/ip/fir_decimator/fir_decimator.xci
# IP: The module: 'fir_decimator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/setuthacker/Xilink_Projects/Multirate_DSP_Final/Multirate_DSP_Final.gen/sources_1/ip/fir_decimator/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_decimator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/setuthacker/Xilink_Projects/Multirate_DSP_Final/Multirate_DSP_Final.gen/sources_1/ip/fir_decimator/fir_decimator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_decimator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
