`timescale 1ns / 1ps

module tb_multirate_system();

    // -------------------------------------------------------------------------
    // 1. Signal Declarations
    // -------------------------------------------------------------------------
    reg clk;
    reg reset;
    
    reg [15:0]  s_axis_input_tdata;
    reg         s_axis_input_tvalid;
    
    wire [63:0] m_axis_output_tdata;
    wire        m_axis_output_tvalid;
    
    wire [15:0] probe_decimated_tdata;
    wire        probe_decimated_tvalid;

    // -------------------------------------------------------------------------
    // 2. Instantiate the Device Under Test (DUT)
    // -------------------------------------------------------------------------
    multirate_system dut (
        .clk                    (clk),
        .reset                  (reset),
        
        .s_axis_input_tdata     (s_axis_input_tdata),
        .s_axis_input_tvalid    (s_axis_input_tvalid),
        
        .m_axis_output_tdata    (m_axis_output_tdata),
        .m_axis_output_tvalid   (m_axis_output_tvalid),
        
        .probe_decimated_tdata  (probe_decimated_tdata),
        .probe_decimated_tvalid (probe_decimated_tvalid)
    );

    // -------------------------------------------------------------------------
    // 3. Clock Generation (120 MHz)
    // -------------------------------------------------------------------------
    // 1 / 120 MHz = 8.333 ns period. Half period = 4.167 ns.
    initial begin
        clk = 0;
        forever #4.167 clk = ~clk; 
    end

    // -------------------------------------------------------------------------
    // 4. Memory and File I/O Setup
    // -------------------------------------------------------------------------
    // Array to hold the 4096 samples from Python
    reg [15:0] input_memory [0:4095]; 
    
    // File descriptors for saving outputs
    integer fd_decimated;
    integer fd_interpolated;
    integer i;

    // -------------------------------------------------------------------------
    // 5. Main Stimulus Block (Injecting the Signal)
    // -------------------------------------------------------------------------
    initial begin
        // Initialize Inputs
        reset = 1;
        s_axis_input_tdata = 0;
        s_axis_input_tvalid = 0;
        
        // Load the input signal generated by Python using the absolute path
        $readmemh("D:/Learning/Signal_Processing/Apexplus_technology/input_signal.txt", input_memory);
        
        // Open output files for writing
        fd_decimated = $fopen("decimated_signal.txt", "w");
        fd_interpolated = $fopen("interpolated_signal.txt", "w");
        
        if (fd_decimated == 0 || fd_interpolated == 0) begin
            $display("ERROR: Could not open output files.");
            $finish;
        end
        
        // Wait 100 ns for global reset to finish
        #100;
        reset = 0;
        #20;
        
        // Feed the data into the system one sample per clock cycle
        for (i = 0; i < 4096; i = i + 1) begin
            @(posedge clk);
            s_axis_input_tdata  = input_memory[i];
            s_axis_input_tvalid = 1;
        end
        
        // Stop feeding data
        @(posedge clk);
        s_axis_input_tvalid = 0;
        
        // Wait enough time for the pipeline to flush all the way through the filters
        #5000;
        
        // Close files and end simulation
        $fclose(fd_decimated);
        $fclose(fd_interpolated);
        $display("Simulation Complete. Output files generated.");
        $finish;
    end

    // -------------------------------------------------------------------------
    // 6. Capture Block: Decimated Signal (Downsampled to 40 MHz)
    // -------------------------------------------------------------------------
    // The tvalid signal ensures we ONLY capture when a new valid sample exists,
    // naturally preventing repeating samples.
    always @(posedge clk) begin
        if (probe_decimated_tvalid) begin
            $fdisplay(fd_decimated, "%04X", probe_decimated_tdata);
        end
    end

    // -------------------------------------------------------------------------
    // 7. Capture Block: Interpolated Signal (Upsampled to 480 MHz)
    // -------------------------------------------------------------------------
    // The output is 64-bits wide containing 4 parallel 16-bit samples.
    // We slice the 64-bit bus into four 16-bit chunks and write them to 
    // the text file sequentially so Python can read them easily as a 1D array.
    always @(posedge clk) begin
        if (m_axis_output_tvalid) begin
            // Writing from LSB to MSB (Oldest sample to newest sample in time)
            $fdisplay(fd_interpolated, "%04X", m_axis_output_tdata[15:0]);
            $fdisplay(fd_interpolated, "%04X", m_axis_output_tdata[31:16]);
            $fdisplay(fd_interpolated, "%04X", m_axis_output_tdata[47:32]);
            $fdisplay(fd_interpolated, "%04X", m_axis_output_tdata[63:48]);
        end
    end

endmodule